# Lista Mestra de Aulas - MedCof Extensivo 2026
# Formato: (Nome da Aula, Grande Área)

DADOS_LIMPOS = [
    # --- BLOCO 1 ---
    ("Avaliação Global do Hemograma", "Clínica Médica"),
    ("Anemias Hipoproliferativas I", "Clínica Médica"),
    ("Anemias Hipoproliferativas II", "Clínica Médica"),
    ("Modificações do Organismo Materno", "Ginecologia e Obstetrícia"),
    ("Assistência ao Pré-Natal", "Ginecologia e Obstetrícia"),
    ("Ultrassonografia em Obstetrícia", "Ginecologia e Obstetrícia"),
    ("Aleitamento Materno", "Pediatria"),
    ("Alimentação Infantil", "Pediatria"),
    
    # --- BLOCO 2 ---
    ("Desenvolvimento Infantil", "Pediatria"),
    ("Alterações no Neurodesenvolvimento - TEA e TDAH", "Pediatria"),
    ("Níveis de Prevenção", "Preventiva"),
    ("Indicadores de Saúde", "Preventiva"),
    ("Introdução ao Trauma e Atendimento Inicial", "Cirurgia"),
    ("Trauma: Vias aéreas", "Cirurgia"),
    ("Choque e Ressuscitação Hemostática", "Cirurgia"),
    ("Neurovascular I: AIT e AVCI", "Clínica Médica"),
    ("Neurovascular II: HSA e AVCh", "Clínica Médica"),
    ("Anatomia Pélvica Feminina", "Ginecologia e Obstetrícia"),
    ("Embriologia do Sistema Genital Feminino", "Ginecologia e Obstetrícia"),
    ("Malformações Mullerianas", "Ginecologia e Obstetrícia"),

    # --- BLOCO 3 ---
    ("Febre sem Sinais Localizatórios", "Pediatria"),
    ("Síndrome Nefrítica e Nefrótica", "Pediatria"),
    ("Doença Renal Crônica e LRA em Pediatria", "Pediatria"),
    ("Testes Diagnósticos", "Preventiva"),
    ("Assistência ao Pré-Natal na APS", "Preventiva"),
    ("Trauma: Medidas Auxiliares e FAST", "Cirurgia"),
    ("Trauma: Populações especiais", "Cirurgia"),
    ("Trauma de Tórax", "Cirurgia"),
    ("Sífilis", "Clínica Médica"),

    # --- BLOCO 4 ---
    ("Dispepsia, DRGE e Barret", "Clínica Médica"),
    ("Úlcera péptica e H. pylori", "Clínica Médica"),
    ("Corrimentos Vaginais", "Ginecologia e Obstetrícia"),
    ("Doença Inflamatória Pélvica Aguda", "Ginecologia e Obstetrícia"),
    ("Úlceras Genitais", "Ginecologia e Obstetrícia"),
    ("Alergia Alimentar, Refluxo e Constipação (Ped)", "Pediatria"),
    ("Diarreia Crônica (Ped)", "Pediatria"),
    ("Violência Contra a Criança e o Adolescente", "Pediatria"),
    ("Determinação Social do Processo Saúde-Doença", "Preventiva"),
    ("Trauma Abdominal", "Cirurgia"),
    ("Trauma Urológico", "Cirurgia"),
    ("Artrite Reumatoide", "Clínica Médica"),

    # --- BLOCO 5 ---
    ("Espondiloartrites", "Clínica Médica"),
    ("Artrites Microcristalinas (Gota e CPPD)", "Clínica Médica"),
    ("Osteoartrite e Fibromialgia", "Clínica Médica"),
    ("Assistência ao Parto", "Ginecologia e Obstetrícia"),
    ("Sofrimento Fetal Agudo", "Ginecologia e Obstetrícia"),
    ("Crescimento e Baixa Estatura", "Pediatria"),
    ("Obesidade e Síndrome Metabólica (Ped)", "Pediatria"),
    ("Puberdade", "Pediatria"),
    ("Desnutrição e Vitaminas", "Pediatria"),
    ("Redes de Atenção à Saúde", "Preventiva"),
    ("Atenção Primária à Saúde", "Preventiva"),
    ("Trauma de Pelve", "Cirurgia"),
    ("Trauma Cranioencefálico", "Cirurgia"),
    ("Trauma Raquimedular", "Cirurgia"),
    ("Trauma Musculoesquelético", "Cirurgia"),
    ("Trauma de Pescoço", "Cirurgia"),

    # --- BLOCO 6 ---
    ("Dor Torácica Coronariana", "Clínica Médica"),
    ("Dor Torácica Não Coronariana", "Clínica Médica"),
    ("Fisiologia Menstrual", "Ginecologia e Obstetrícia"),
    ("Amenorreia Primária", "Ginecologia e Obstetrícia"),
    ("Esteroidogênese", "Ginecologia e Obstetrícia"),
    ("Politrauma e Afogamento (Ped)", "Pediatria"),
    ("Queimaduras (Ped)", "Pediatria"),
    ("TCE e Hipertensão Intracraniana (Ped)", "Pediatria"),
    ("Diarreia Aguda (Ped)", "Pediatria"),
    ("Classificação dos Estudos Epidemiológicos", "Preventiva"),
    ("Associação x Causalidade", "Preventiva"),
    ("Rastreamentos", "Preventiva"),
    ("Trauma: Encerramento", "Cirurgia"),
    ("Queimaduras (Cirurgia)", "Cirurgia"),
    ("Escroto Agudo", "Cirurgia"),
    ("Priapismo", "Cirurgia"),

    # --- BLOCO 7 ---
    ("Gasometria Arterial", "Clínica Médica"),
    ("Distúrbios do Sódio", "Clínica Médica"),
    ("Distúrbios do Potássio", "Clínica Médica"),
    ("Reações Alérgicas", "Clínica Médica"),
    ("Amenorreia Secundária", "Ginecologia e Obstetrícia"),
    ("Hiperprolactinemia", "Ginecologia e Obstetrícia"),
    ("SOP (Síndrome dos Ovários Policísticos)", "Ginecologia e Obstetrícia"),
    ("Infecções de Vias Aéreas Superiores (IVAS)", "Pediatria"),
    ("Autoinflamatórias (Ped)", "Pediatria"),
    ("Pneumonias (Ped)", "Pediatria"),
    ("Bronquiolite e Coqueluche", "Pediatria"),
    ("COVID (Ped)", "Pediatria"),
    ("Estudos Transversais", "Preventiva"),
    ("Estudos Longitudinais: Coorte e Caso-Controle", "Preventiva"),
    ("Abdome Agudo: Introdução", "Cirurgia"),
    ("Apendicite Aguda", "Cirurgia"),
    ("Cicatrização e Lesões por Pressão", "Cirurgia"),
    ("Fios de Sutura e Anestésicos Locais", "Cirurgia"),
    ("Antibióticos", "Clínica Médica"),
    ("Anemias Hemolíticas", "Clínica Médica"),

    # --- BLOCO 8 ---
    ("Oncologia: emergências e cuidados paliativos", "Clínica Médica"),
    ("Infecções e Gravidez", "Ginecologia e Obstetrícia"),
    ("Rotura Prematura de Membranas Ovulares", "Ginecologia e Obstetrícia"),
    ("Violência Sexual", "Ginecologia e Obstetrícia"),
    ("Interrupção Legal da Gestação", "Ginecologia e Obstetrícia"),
    ("Reanimação Neonatal", "Pediatria"),
    ("Infecções Congênitas", "Pediatria"),
    ("Icterícia e Colestase Neonatal", "Pediatria"),
    ("História e Princípios do SUS", "Preventiva"),
    ("Cardiologia na APS", "Preventiva"),
    ("Urgências da Vesícula Biliar", "Cirurgia"),
    ("Câncer de Esôfago", "Cirurgia"),
    ("Cefaleias", "Clínica Médica"),

    # --- BLOCO 9 ---
    ("Avaliação Geriátrica Ampla", "Clínica Médica"),
    ("Grandes Síndromes Geriátricas", "Clínica Médica"),
    ("Avaliação de enzimas hepáticas", "Clínica Médica"),
    ("Doenças hepáticas: CBP, CEP, HAI, Wilson", "Clínica Médica"),
    ("Abortamento", "Ginecologia e Obstetrícia"),
    ("Gestação Ectópica", "Ginecologia e Obstetrícia"),
    ("Doença Trofoblástica Gestacional", "Ginecologia e Obstetrícia"),
    ("Dermatite Atópica (Ped)", "Pediatria"),
    ("Dermatoses e Infecções de Partes Moles (Ped)", "Pediatria"),
    ("Legislação do SUS I: Leis Orgânicas", "Preventiva"),
    ("Pancreatite Aguda", "Cirurgia"),
    ("Diverticulite Aguda", "Cirurgia"),
    ("Abscesso Hepático", "Cirurgia"),
    ("Disfagia e Acalasia", "Cirurgia"),
    ("Hernias de Hiato", "Cirurgia"),

    # --- BLOCO 10 ---
    ("Coagulação e Hemostasia", "Clínica Médica"),
    ("Hemoterapia", "Clínica Médica"),
    ("Cirrose Hepática I e II", "Clínica Médica"),
    ("Pneumonia Adquirida na Comunidade", "Clínica Médica"),
    ("Derrame Pleural", "Clínica Médica"),
    ("Placenta Prévia", "Ginecologia e Obstetrícia"),
    ("Descolamento Prematuro de Placenta", "Ginecologia e Obstetrícia"),
    ("Sangramentos da Segunda Metade da Gestação", "Ginecologia e Obstetrícia"),
    ("Anemia Falciforme (Ped)", "Pediatria"),
    ("Anemia Ferropriva e Talassemia (Ped)", "Pediatria"),
    ("Distúrbios Hemorrágicos (Ped)", "Pediatria"),
    ("Genética (Ped)", "Pediatria"),
    ("Legislação do SUS II: NOBS, NOAS", "Preventiva"),
    ("Tabagismo", "Preventiva"),
    ("Abdome Agudo Obstrutivo", "Cirurgia"),
    ("Abdome Agudo Perfurativo, Vascular e Hemorrágico", "Cirurgia"),
    ("Câncer de Estômago", "Cirurgia"),
    ("HAS: Ambulatorial e Emergências", "Clínica Médica"),
    ("Insuficiência Cardíaca", "Clínica Médica"),
    ("Espirometria e Asma", "Clínica Médica"),
    ("DPOC", "Clínica Médica"),
    ("BLS e ACLS", "Clínica Médica"),
    ("Síndromes Hipertensivas na Gestação", "Ginecologia e Obstetrícia"),
    
    # --- BLOCO 11 ---
    ("Sangramento Uterino Anormal", "Ginecologia e Obstetrícia"),
    ("Suporte Avançado de Vida em Pediatria (PALS)", "Pediatria"),
    ("Cardiopatias Congênitas", "Pediatria"),
    ("HAS na Pediatria", "Pediatria"),
    ("Miocardite, Síncope, IC (Ped)", "Pediatria"),
    ("Medidas de Associação", "Preventiva"),
    ("Legislação do SUS 3: Decreto 7508/11", "Preventiva"),
    ("Rede de Atenção Psicossocial (RAPS)", "Preventiva"),
    ("Anatomia da Parede Abdominal e Hérnia Inguinal", "Cirurgia"),
    ("Hernioplastia Inguinal", "Cirurgia"),
    ("Outras Neoplasias Gástricas", "Cirurgia"),
    ("Enxertos e Retalhos", "Cirurgia"),
    ("Diabetes: Diagnóstico e Metas", "Clínica Médica"),
    ("Diabetes: Tratamento", "Clínica Médica"),
    ("Emergências Hiperglicêmicas (CAD e EHH)", "Clínica Médica"),
    ("Diabetes na Gestação", "Ginecologia e Obstetrícia"),
    ("Infertilidade", "Ginecologia e Obstetrícia"),
    ("Endometriose", "Ginecologia e Obstetrícia"),
    ("Arboviroses (Ped)", "Pediatria"),
    ("Doenças Exantemáticas", "Pediatria"),
    ("Cetoacidose Diabética (Ped)", "Pediatria"),
    ("Financiamento do SUS", "Preventiva"),
    ("Ensaios Clínicos", "Preventiva"),
    ("Ética em Pesquisa Clínica", "Preventiva"),
    
    # --- BLOCO 12 ---
    ("Síndrome Compartimental Intra-Abdominal", "Cirurgia"),
    ("Hérnias Incisionais", "Cirurgia"),
    ("Outras Hérnias", "Cirurgia"),
    ("Urgências endoscópicas", "Cirurgia"),
    ("Síndrome Metabólica e Obesidade", "Clínica Médica"),
    ("Dislipidemias", "Clínica Médica"),
    ("Doença Hepática Esteatótica Metabólica", "Clínica Médica"),
    ("Incontinência Urinária", "Ginecologia e Obstetrícia"),
    ("Prolapso Genital", "Ginecologia e Obstetrícia"),
    ("Triagens Neonatais", "Pediatria"),
    ("Distúrbios Metabólicos Neonatais", "Pediatria"),
    ("Peçonhentos, Raiva e Tétano (Ped)", "Pediatria"),
    ("Ingestão de Corpo Estranho e BRUE", "Pediatria"),
    ("Significância Estatística: Valor-p e IC", "Preventiva"),
    ("Revisão Sistemática e Metanálise", "Preventiva"),
    ("Medicina Baseada em Evidências", "Preventiva"),
    ("Pré-Operatório", "Cirurgia"),
    ("Uro-Oncologia", "Cirurgia"),
    ("Cirurgia Bariátrica", "Cirurgia"),
    
    # --- BLOCO 13 ---
    ("Vasculites", "Clínica Médica"),
    ("Tuberculose: clínica e diagnóstico", "Clínica Médica"),
    ("Tuberculose: tratamento", "Clínica Médica"),
    ("Avaliação de Vitalidade Fetal", "Ginecologia e Obstetrícia"),
    ("Restrição de Crescimento Intrauterino", "Ginecologia e Obstetrícia"),
    ("Sofrimento Fetal Crônico", "Ginecologia e Obstetrícia"),
    ("Gemelaridade", "Ginecologia e Obstetrícia"),
    ("Convulsão na Emergência e Convulsão Febril", "Pediatria"),
    ("Tuberculose (Ped)", "Pediatria"),
    ("Diabetes no SUS", "Preventiva"),
    ("Estratégia da Saúde da Família", "Preventiva"),
    ("REMIT e pós-operatório", "Cirurgia"),
    ("Complicações pós-operatórias gerais", "Cirurgia"),
    ("Fraturas de face", "Cirurgia"),
    ("Hiperplasia prostática benigna", "Cirurgia"),

    # --- BLOCO 14 ---
    ("Meningites & Encefalites", "Clínica Médica"),
    ("Doenças Neuromusculares e Parkinson", "Clínica Médica"),
    ("Taquiarritmias", "Clínica Médica"),
    ("Bradiarritimias", "Clínica Médica"),
    ("Síncope", "Clínica Médica"),
    ("Doenças Valvares", "Clínica Médica"),
    ("Cardiopatias na Gravidez", "Ginecologia e Obstetrícia"),
    ("Anticoncepção", "Ginecologia e Obstetrícia"),
    ("Kawasaki, Vasculite por IgA e Febre Reumática", "Pediatria"),
    ("Artrite Idiopática Juvenil", "Pediatria"),
    ("Meningite e Encefalite (Ped)", "Pediatria"),
    ("Financiamento da APS", "Preventiva"),
    ("Síndrome Depressiva", "Clínica Médica"),
    ("Síndrome Maníaca", "Clínica Médica"),
    ("Câncer colorretal e Síndromes associadas", "Cirurgia"),
    ("Doenças Orificiais e CEC de Canal Anal", "Cirurgia"),
    ("Doenças da Vesícula Biliar", "Cirurgia"),

    # --- BLOCO 15 ---
    ("Via aérea, intubação e VNI", "Clínica Médica"),
    ("Síndrome do Desconforto Respiratório Agudo (SDRA)", "Clínica Médica"),
    ("Ventilação Mecânica", "Clínica Médica"),
    ("Infecções Nosocomiais", "Clínica Médica"),
    ("Choque", "Clínica Médica"),
    ("Drogas Vasoativas e Sedoanalgesia", "Clínica Médica"),
    ("Vacinação (Adulto/Geral)", "Preventiva"), 
    ("Propedêutica Mamária", "Ginecologia e Obstetrícia"),
    ("Principais Sintomas em Mastologia", "Ginecologia e Obstetrícia"),
    ("Classificação das Lesões Benignas da Mama", "Ginecologia e Obstetrícia"),
    ("Vacinação (Ped)", "Pediatria"),
    ("HIV (Ped)", "Pediatria"),
    ("Ortopedia Pediátrica", "Pediatria"),
    ("Osteomielite e Artrite Séptica (Ped)", "Pediatria"),
    ("Ferramentas da APS/ESF", "Preventiva"),
    ("Síndrome Ansiosa", "Clínica Médica"),
    ("Fígado para perdidos (Anatomia Cirúrgica)", "Cirurgia"),
    ("Nódulos hepáticos benignos", "Cirurgia"),
    ("Ferimento descolante", "Cirurgia"),

    # --- BLOCO 16 ---
    ("Injúria Renal (LRA)", "Clínica Médica"),
    ("Diarreia Agudas e Colite Pseudomembranosa", "Clínica Médica"),
    ("Diarreias Crônicas", "Clínica Médica"),
    ("Doença Inflamatória Intestinal (DII)", "Clínica Médica"),
    ("Doenças Negligenciadas", "Clínica Médica"),
    ("Trabalho de Parto Prematuro", "Ginecologia e Obstetrícia"),
    ("Colo Curto e Incompetência Istmocervical", "Ginecologia e Obstetrícia"),
    ("Hiperplasia Adrenal Congênita (HAC)", "Pediatria"),
    ("Hipotireoidismo (Ped)", "Pediatria"),
    ("Diferenças no Desenvolvimento Sexual (DDS)", "Pediatria"),
    ("Nutrologia em Pediatria", "Pediatria"),
    ("Telessaúde e Publicidade Médica", "Preventiva"),
    ("Método Clínico Centrado na Pessoa e Comunicação", "Preventiva"),
    ("Litíase Renal", "Cirurgia"),
    ("Carcinoma Hepatocelular", "Cirurgia"),
    ("Aneurisma de Aorta", "Cirurgia"),

    # --- BLOCO 17 ---
    ("Lúpus Eritematoso Sistêmico", "Clínica Médica"),
    ("Osteoporose", "Clínica Médica"),
    ("Esclerose Sistêmica", "Clínica Médica"),
    ("Doença de Sjögren", "Clínica Médica"),
    ("Miopatias Autoimunes Sistêmicas", "Clínica Médica"),
    ("Glomerulopatias", "Clínica Médica"),
    ("Intoxicações Exógenas", "Clínica Médica"),
    ("Hemorragia Pós-Parto", "Ginecologia e Obstetrícia"),
    ("Puerpério", "Ginecologia e Obstetrícia"),
    ("Asma (Ped)", "Pediatria"),
    ("Fibrose Cística e Diferenciais", "Pediatria"),
    ("Imunodeficiências para o Pediatra", "Pediatria"),
    ("Vigilância em Saúde", "Preventiva"),
    ("Registro de Saúde Orientado por Problemas (ReSOAP)", "Preventiva"),
    ("Metástases hepáticas de câncer colorretal", "Cirurgia"),
    ("Adenocarcinoma de pâncreas e tumores periampulares", "Cirurgia"),
    ("Quiz: Fígado e Vias Biliares", "Cirurgia"),

    # --- BLOCO 18 ---
    ("HIV e Doenças Oportunistas", "Clínica Médica"),
    ("Fisiologia da Tireoide e Hipotireoidismo", "Clínica Médica"),
    ("Hipertireoidismo e Tireotoxicose", "Clínica Médica"),
    ("Epilepsia", "Clínica Médica"),
    ("Esclerose Múltipla e Neuromielite Óptica", "Clínica Médica"),
    ("Câncer de Colo de Útero: Rastreamento", "Ginecologia e Obstetrícia"),
    ("Câncer de Colo de Útero: Diagnóstico e Tratamento", "Ginecologia e Obstetrícia"),
    ("Doenças da Vulva e da Vagina", "Ginecologia e Obstetrícia"),
    ("Sepse Neonatal", "Pediatria"),
    ("Desconforto Respiratório Neonatal", "Pediatria"),
    ("Outras Doenças Neonatais", "Pediatria"),
    ("Nutrição do Pré-Termo", "Pediatria"),
    ("Processo Epidêmico", "Preventiva"),
    ("Abordagem Familiar e Comunitária", "Preventiva"),
    ("Síndrome de Fournier", "Cirurgia"),
    ("Ortopedia Geral", "Cirurgia"),
    ("Trombose Venosa Profunda (TVP)", "Cirurgia"),
    ("Pneumotórax (Cirúrgico)", "Cirurgia"),

    # --- BLOCO 19 ---
    ("Tromboembolismo Pulmonar (TEP)", "Clínica Médica"),
    ("Distúrbios do Sono", "Clínica Médica"),
    ("Doença Pulmonar Intersticial (DPI)", "Clínica Médica"),
    ("Nódulo Pulmonar", "Clínica Médica"),
    ("Adrenal", "Clínica Médica"),
    ("Síndrome de Cushing", "Clínica Médica"),
    ("Disfagia, Esofagite Eosinofilica e Acalasias", "Clínica Médica"),
    ("Câncer de Mama: Rastreamento", "Ginecologia e Obstetrícia"),
    ("Câncer de Mama: Fatores de Risco e CDIS", "Ginecologia e Obstetrícia"),
    ("Câncer de Mama: Doença Invasiva", "Ginecologia e Obstetrícia"),
    ("Parasitoses Intestinais (Ped)", "Pediatria"),
    ("Neoplasias Pediátricas", "Pediatria"),
    ("Acidente de Trabalho", "Preventiva"),
    ("Síndrome Psicótica", "Clínica Médica"),
    ("Psicofarmacologia", "Clínica Médica"),
    ("Oncocirurgia Geral", "Cirurgia"),
    ("Isquemia de Membros Inferiores", "Cirurgia"),

    # --- BLOCO 20 ---
    ("Infecção do Trato Urinário (ITU)", "Clínica Médica"),
    ("Distúrbios Hidroeletrolíticos (Ca, P, Mg)", "Clínica Médica"),
    ("Doença Renal Crônica", "Clínica Médica"),
    ("Síndrome Climatérica", "Ginecologia e Obstetrícia"),
    ("Terapia Hormonal", "Ginecologia e Obstetrícia"),
    ("Tumores Anexiais", "Ginecologia e Obstetrícia"),
    ("Câncer de Ovário", "Ginecologia e Obstetrícia"),
    ("ITU na Pediatria", "Pediatria"),
    ("Sedoanalgesia e Intubação (Ped)", "Pediatria"),
    ("Sepse Pediátrica", "Pediatria"),
    ("Choque e Drogas Vasoativas (Ped)", "Pediatria"),
    ("Pneumoconioses", "Preventiva"),
    ("Tuberculose e Hanseníase na APS", "Preventiva"),
    ("Saúde Socioecológica e Global", "Preventiva"),
    ("Cirurgia: Resumão/Encerramento", "Cirurgia"),
    ("Neoplasias Císticas Pancreáticas", "Cirurgia"),
    ("Pancreatite Crônica", "Cirurgia"),
    ("Trauma Vascular", "Cirurgia"),
    ("Estenose Carotídea", "Cirurgia"),
    ("Câncer de Pulmão (Cirúrgico)", "Cirurgia"),

    # --- BLOCO 21 ---
    ("Depressão e Delirium no Idoso", "Clínica Médica"),
    ("Insuficiência Cognitiva: Demências", "Clínica Médica"),
    ("Hiperplasia Endometrial", "Ginecologia e Obstetrícia"),
    ("Câncer de Endométrio", "Ginecologia e Obstetrícia"),
    ("Intercorrências Clínicas na Gestação", "Ginecologia e Obstetrícia"),
    ("Cirurgia Pediátrica no PS", "Pediatria"),
    ("Uropediatria e Hérnias", "Pediatria"),
    ("Malformações Congênitas", "Pediatria"),
    ("Declaração de Óbito, Atestados e Laudos", "Preventiva"),
    ("Atenção à Saúde de Populações Específicas", "Preventiva"),
    ("Videolaparoscopia e Eletrocirurgia", "Cirurgia"),
    ("Tumores Neuroendócrinos (Pâncreas/Vias Biliares)", "Cirurgia"),
    ("Nutrição Perioperatória", "Cirurgia"),
    ("Diagnósticos Diferenciais das Massas Cervicais", "Cirurgia"),
    ("Insuficiência Venosa Crônica", "Cirurgia"),
    ("Síndromes Compressivas Vasculares", "Cirurgia"),

    # --- BLOCO 22 ---
    ("Doenças Virais e Pandêmicas", "Clínica Médica"),
    ("Arboviroses (Adulto)", "Clínica Médica"),
    ("Icterícias Febris e Febre Maculosa", "Clínica Médica"),
    ("Hepatites Virais", "Clínica Médica"),
    ("Técnicas de Reprodução Assistida", "Ginecologia e Obstetrícia"),
    ("Cuidado à Saúde LGBTQIAPN+", "Ginecologia e Obstetrícia"),
    ("Medicina do Adolescente", "Pediatria"),
    ("Ética em Pediatria", "Pediatria"),
    ("Ética Médica", "Preventiva"),
    ("Intoxicações, PAIRO e Burnout", "Preventiva"),
    ("Dermatologia na APS", "Preventiva"),
    ("Tumores do Intestino Delgado", "Cirurgia"),
    ("Doenças Cirúrgicas do Baço", "Cirurgia"),
    ("CEC de Cabeça e Pescoço", "Cirurgia"),
    ("Doenças Traqueais", "Cirurgia"),
    ("Bronquiectasias e Hemoptise (Cirurgia)", "Cirurgia"),

    # --- BLOCO 23 ---
    ("Hiperaldosteronismo Primário", "Clínica Médica"),
    ("Feocromocitoma", "Clínica Médica"),
    ("Prolactinomas", "Clínica Médica"),
    ("Oncohematologia", "Clínica Médica"),
    ("Cirurgia Ginecológica: Princípios e Complicações", "Ginecologia e Obstetrícia"),
    ("Transtornos Psiquiátricos na Gestação/Pós-parto", "Ginecologia e Obstetrícia"),
    ("Emergências Psiquiátricas", "Clínica Médica"),
    ("Violências e Vulnerabilidade", "Preventiva"),
    ("Saúde Privada, Suplementar e Judicialização", "Preventiva"),
    ("Psiquiatria da Infância e Adolescência", "Pediatria"),
    ("Epilepsias na Infância", "Pediatria"),
    ("Cisto Pilonidal", "Cirurgia"),
    ("Anomalias Congênitas em Cabeça e Pescoço", "Cirurgia"),
    ("Mediastino", "Cirurgia"),

    # --- BLOCO 24 ---
    ("Dermatologia", "Clínica Médica"),
    ("Medicina Fetal (G.O)", "Ginecologia e Obstetrícia"),
    ("Otites, Perda Auditiva, Rinossinusites (Ped)", "Pediatria"),
    ("Rinites e Afecções da Laringe e Faringe (Ped)", "Pediatria"),
    ("Transtornos Alimentares e de Personalidade", "Clínica Médica"),
    ("Endoscopia", "Cirurgia"),
    ("Cabeça e Pescoço: Tireóide e Paratireóide", "Cirurgia"),

    # --- BLOCO 25 ---
    ("Neurocirurgia", "Cirurgia"),
    ("Otologia I", "Cirurgia"),
    ("Otologia II", "Cirurgia"),
    ("Oftalmologia para o Generalista I", "Cirurgia"),
    ("Trombofilias na Gestação e Puerpério", "Ginecologia e Obstetrícia"),
    ("Doença Hemolítica Perinatal", "Ginecologia e Obstetrícia"),
    ("Oftalmopediatria", "Pediatria"),
    ("Saúde do Trabalhador", "Preventiva"),
    ("Anestesiologia", "Cirurgia"),

    # --- BLOCO 26 (Reta Final) ---
    ("Rinologia", "Cirurgia"),
    ("Bucofaringolaringologia I", "Cirurgia"),
    ("Bucofaringolaringologia II", "Cirurgia"),
    ("Oftalmologia para o Generalista II", "Cirurgia"),
    ("Outras Urgências Ginecológicas", "Ginecologia e Obstetrícia"),
    ("Malformações do Sistema Nervoso", "Pediatria"),
    ("Doenças Neuromusculares na Infância", "Pediatria"),
    ("Transtornos Relacionados a Substâncias (Álcool)", "Clínica Médica"),
    ("Preventiva: Reta Final", "Preventiva"),
    ("Cirurgia Cardíaca", "Cirurgia"),
    ("Tromboelastograma", "Cirurgia"),
]